---

- name: Configure RabbitMQ for Sensu client
  template:
    src: rabbitmq.json.j2
    dest: /etc/sensu/conf.d/rabbitmq.json
  register: sensu_client_rabbitmq_config_result
  notify:
    - Restart sensu-client {{ sensu_from }}
  tags:
    - sensu_config

- name: Create Sensu client config
  template:
    src: client.json.j2
    dest: /etc/sensu/conf.d/client.json
  register: sensu_client_config_result
  notify:
    - Restart sensu-client {{ sensu_from }}
  tags:
    - sensu_config

- name: Make sure sensu-client is enabled
  service:
    name: sensu-client
    enabled: yes
  tags:
    - sensu_service

- name: Make sure sensu-client is started
  service:
    name: sensu-client
    state: started
  when: >
    (
        sensu_client_rabbitmq_config_result is not defined and
        sensu_client_config_result is not defined) or
    (
        not sensu_client_rabbitmq_config_result.changed and
        not sensu_client_config_result.changed)
  register: sensu_client_service_started
  tags:
    - sensu_service
