---

- name: Create Sensu YUM repo file
  yum_repository:
    name: sensu-main
    description: Sensu YUM repo
    baseurl: "{{ sensu_yumrepo_url }}"
    gpgcheck: 0
    params: "{{ sensu_yumrepo_params }}"
  tags:
    - sensu_pkg

- name: Install Sensu
  package:
    name: "{{ sensu_pkg }}"
    state: present
  register: sensu_installed
  tags:
    - sensu_pkg

- name: Install Sensu - restart server
  debug:
    msg: ""
  changed_when: >
    sensu_install_server and
    sensu_installed.changed
  notify:
    - Restart sensu-server {{ sensu_from }}
  tags:
    - sensu_pkg

- name: Install Sensu - restart api
  debug:
    msg: ""
  changed_when: >
    sensu_install_api and
    sensu_installed.changed
  notify:
    - Restart sensu-api {{ sensu_from }}
  tags:
    - sensu_pkg

- name: Install Sensu - restart client
  debug:
    msg: ""
  changed_when: >
    sensu_install_client and
    sensu_installed.changed
  notify:
    - Restart sensu-client {{ sensu_from }}
  tags:
    - sensu_pkg
