---

- name: Restart sensu-server {{ sensu_from }}
  service:
    name: sensu-server
    state: restarted
  when: >
    sensu_server_service_started is not defined or
    not sensu_server_service_started.changed

- name: Restart sensu-api {{ sensu_from }}
  service:
    name: sensu-api
    state: restarted
  when: >
    sensu_api_service_started is not defined or
    not sensu_api_service_started.changed

- name: Restart sensu-client {{ sensu_from }}
  service:
    name: sensu-client
    state: restarted
  when: >
    sensu_client_service_started is not defined or
    not sensu_client_service_started.changed
